name: Cypress Tests

on:
  push:
    branches:
      - main
      - Ex

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Set Environment (Dev/Staging)
        run: |
          echo "CYPRESS_ENV=${{ secrets.CYPRESS_ENV }}" >> $GITHUB_ENV
        env:
          CYPRESS_ENV: ${{ github.event.inputs.env }}

      - name: Run Cypress tests
        run: |
          if [ "${{ env.CYPRESS_ENV }}" == "staging" ]; then
            npx cypress run --config-file cypress.staging.json
          else
            npx cypress run --config-file cypress.dev.json
          fi
