name: Cypress Tests

on:
  push:
    branches:
      - Ex

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
            path: ~/.cache/Cypress
            key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
    

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
